### ISSUE TITLE
Samples on The IReliableDispatcher<T> wiki and sourcecode 

### ISSUE THREAD

**Issue by FunksMaName** [wc2/micro-service-fabric#22]
Hi, Quick question

looking at the sample code and the wiki, should the IReliableDispatcher<T> not be dequeuing stuff in the CounterService?

So, rather than have 

`        async Task<int> IQueryCounter.GetCounterAsync()
        {
            var counters = await StateManager.GetOrAddAsync<IReliableDictionary<string, int>>("Counters").ConfigureAwait(false);
            int counter;

            using (var transaction = StateManager.CreateTransaction())
            {
                var counterValue = await counters.TryGetValueAsync(transaction, "Counter").ConfigureAwait(false);
                counter = counterValue.HasValue
                    ? counterValue.Value
                    : 0;
                await transaction.CommitAsync().ConfigureAwait(false);
            }

            return counter;
        }`

You have something similar to: 

`var counters = await StateManager.GetOrAddAsync<IReliableQueue<int>>("CounterIncrements").ConfigureAwait(false);
            int counter;

            using (var transaction = StateManager.CreateTransaction())
            {
                var counterValue = await counters.TryDequeueAsync(transaction).ConfigureAwait(false);
                counter = counterValue.HasValue
                    ? counterValue.Value
                    : 0;
                await transaction.CommitAsync().ConfigureAwait(false);
            }

            return counter;`

**Comment by FunksMaName** [comment]
Just gone though the source code, implementation is correct

**Comment by WonkiDonk** [comment]
👍
